CREATE DATABASE t8grupo8;
USE t8grupo8;

CREATE TABLE teams(
    TEAM_ID       INTEGER  NOT NULL,
    NICKNAME      VARCHAR(13) NOT NULL,
    YEARFOUNDED   INTEGER  NOT NULL,
    CITY          VARCHAR(13) NOT NULL,
    STATE         VARCHAR(30) NOT NULL,
    ARENA         VARCHAR(27) NOT NULL,
    ARENACAPACITY INTEGER,
    PRIMARY KEY(team_id)
);
