CREATE DATABASE t8grupo8;
USE t8grupo8;

CREATE TABLE rankings(
    RANKING_ID INTEGER  NOT NULL,
    TEAM_ID    INTEGER  NOT NULL,
    SEASON_ID  INTEGER  NOT NULL,
    TEAM       VARCHAR(13) NOT NULL,
    HOME_WIN   INTEGER  NOT NULL,
    HOME_FAIL  INTEGER  NOT NULL,
    ROAD_WIN   INTEGER  NOT NULL,
    ROAD_FAIL  INTEGER  NOT NULL,
    PRIMARY KEY(ranking_id),
    FOREIGN KEY(team_id) REFERENCES teams(team_id)
);